---
kasten:
  locationProfile:
    name: default-location-profile        
    bucketName: your-bucket-name          # Replace with the AWS S3 bucket name to store backup data
    region: us-east-1                     # Replace with the AWS S3 bucket region
    immutable: false                      # Set true only if AWS S3 bucket was created with Versioning/Object Lock enabled; otherwise false 
    protectionPeriod: 120h0m0s            # Adjust to specify amount of time for retained RestorePoints to remain immutable. Caution!

  policyDefaults:
    presetName: daily-backup
    ignoreExceptions: false