apiVersion: config.kio.kasten.io/v1alpha1
kind: PolicyPreset
metadata:
  name: daily-backup
  namespace: kasten-io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  backup:
    frequency: "@daily"
    backupWindow:
      start:
        hour: 0
        minute: 0
      end:
        hour: 7
        minute: 30
    enableStaggering: true
    retention:
      daily: 7
      weekly: 4
      monthly: 12
      yearly: 7
    profile:
      name: {{ .Values.kasten.policyDefaults.locationProfileName }}
      namespace: kasten-io
    imageRepoProfile:
      name: {{ .Values.kasten.policyDefaults.locationProfileName }}
      namespace: kasten-io
  export:
    profile:
      name: {{ .Values.kasten.policyDefaults.locationProfileName }}
      namespace: kasten-io
    exportData:
      enabled: true