---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: {{ .Values.kasten.locationProfile.name }}
  namespace: kasten-io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: Location
  locationSpec:
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: Secret
        name: external-s3-profile-secret
        namespace: kasten-io
    type: ObjectStore
    objectStore:
      name: {{ .Values.kasten.locationProfile.bucketName }}
      objectStoreType: S3
      region: {{ .Values.kasten.locationProfile.region }}
      {{ if .Values.kasten.locationProfile.immutable }}
      protectionPeriod: {{ .Values.kasten.locationProfile.protectionPeriod }}
      {{- end }}