---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: external-s3-profile-secret
  namespace: kasten-io
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: external-s3-profile-secret
    creationPolicy: Owner
    # template:
    #   engineVersion: v2
    #   type: secrets.kanister.io/aws
    #   data:
    #     aws_access_key_id: "{{ .aws_access_key_id }}" 
    #     aws_secret_access_key: "{{ .aws_secret_access_key }}"
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: {{ .Values.awsCreds.key }}
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: {{ .Values.awsCreds.key }}
      property: aws_secret_access_key
