---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: kastendr-passphrase-secret
  namespace: kasten-io
spec:
  refreshInterval: 90s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: k10-dr-secret
  dataFrom:
  - extract:
      key: {{ .Values.kasten.kdrSecretKey }}
