apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: veeam-kasten-config-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: veeam-kasten-config-clusterrole
subjects:
- kind: ServiceAccount
  name: veeam-kasten-config-sa
  namespace: kasten-io