---
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

kastendrPassphrase:
  key: secret/data/hub/kastendr-passphrase

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest